use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'TUKit_Example' do
  pod 'TUKit', :path => '../'

  target 'TUKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
