default_platform(:ios)
import_from_git(url: 'http://nas.iliunian.com:82/liunian/FastlaneStandardSetup.git',
          path: 'Fastfile')
platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
